apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
  namespace: csi-basics
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
